name: sdui
channels:
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu116
    - torch==1.13.1+cu116; sys_platform != "darwin"
    - torch==1.13.*; sys_platform == "darwin"
    - ninja==1.11.*
    - transformers==4.25.*
    - accelerate==0.15.*
    - scipy==1.9.*
    - diffusers[torch]==0.10.2
    - gdown
    - pyviewer

# conda env create --force --file environment.yml
