name: ldm
channels:
  - pytorch-nightly
  - defaults
dependencies:
  - python=3.10.4
  - onnx
  - pip=22.1.2
  - pip:
    - jsonmerge
    - clean-fid
    - resize-right
    - torchdiffeq
    - whl/torch-1.13.0a0+gitc9f7557-cp310-cp310-macosx_12_0_arm64.whl
    - whl/tvm-0.9.0-cp310-cp310-macosx_12_0_arm64.whl
    - torchvision
    - imgui[glfw]==1.4
    - albumentations==0.4.6
    - diffusers
    - gdown
    - opencv-python==4.6.0.66
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.19.2
    - torchmetrics==0.6.0
    - kornia==0.6
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
