name: ldm
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10.4
  - pip=22.1.2
  - pytorch=1.13
  - torchvision=0.13
  - pip:
    - jsonmerge
    - clean-fid
    - resize-right
    - torchdiffeq
    - protobuf==3.20.1
    - albumentations==0.4.6
    - gdown
    - opencv-python==4.6.0.66
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - torchmetrics==0.6.0
    - kornia==0.6
    - transformers
    - accelerate
    - scipy
    - diffusers[torch]
    - ninja
    - git+https://github.com/facebookresearch/xformers.git@main#egg=xformers  # needs torch during installation...
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e git+https://github.com/harskish/pyviewer.git#egg=pyviewer
    - -e .

# conda env create --force --file environment-mac.yaml
